export default {
  ACTIVITY_DEFINITION_STACK: 'ACTIVITY_DEFINITION_STACK',
  PLANTATION_DEFINITION_STACK: 'PLANTATION_DEFINITION_STACK',
  MODULES_DEFINITION_STACK: 'MODULES_DEFINITION_STACK',
  EXPENSES_OR_ITEMS_DEFINITION_STACK: 'EXPENSES_OR_ITEMS_DEFINITION_STACK',
  GROUP_DEFINITION_STACK: 'GROUP_DEFINITION_STACK',
  PRODUCT_DEFINITION_STACK: 'PRODUCT_DEFINITION_STACK',
  DESTINATION_DEFINITION_STACK: 'DESTINATION_DEFINITION_STACK',
  EMPLOYEE_DEFINITION_STACK: 'EMPLOYEE_DEFINITION_STACK',
  MACHINE_DEFINITION_STACK: 'MACHINE_DEFINITION_STACK'
} as const
