export const GLOBAL_STRINGS = {
  KEY_AUTH: "__genesis__agricola__auth__",
  KEY_THEME: "__genesis__agricola__theme__",
  USER: "Usuario",
  PASSWORD: "Contraseña",
  APP_NAME: "Genesis Agricola",
  USER_ENTER: "Ingrese su usuario",
  LOGIN_BUTTON: "Ingresar",
  DEFINITION: "Definición",
  RECORD: "Registro",
  REPORT: "Informe",
  ACTIVITIES: "Actividades",
  PLANTATION: "Plantación",
  MODULES: "Módulos",
  GASTOS_RUBROS: "Gastos Rubros",
  GROUP: "Grupo",
  PRODUCTS: "Productos",
  DESTINATIONS: "Destinos",
  EMPLOYEES: "Empleados",
  MACHINIES: "Maquinarias",
  SETTINGS: "Configuración",
  CONFIG_CONECTION: "Configuración de conexión",
  CONFIG_CONECTION_ABB: "Config. de conexión",
  DARK_MODE: "Modo oscuro",
  ADD_URL_OR_SCAN_QR: "Agregue una URL o escanee un código QR",
  URL: "URL",
} as const;
